name: the_enest_english_grammar_test
description: The Enest English Grammar Test With Explanation

version: 1.0.4+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #Core dependencies
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_auth: ^3.0.1
  fluro: ^2.0.3
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.6
  percent_indicator: ^3.0.1
  intl: ^0.17.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  package_info: ^2.0.2
  get: ^4.2.4
  http: ^0.13.3
  google_fonts: ^2.1.0
  audioplayers: ^0.19.1
  hive: ^2.0.4
  path_provider: ^2.0.2
  animated_widgets: ^1.1.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.5
  flutter_facebook_auth: ^3.5.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  flutter_slidable: ^0.6.0
  dio: ^4.0.0
  uuid: ^3.0.4
  confetti: ^0.6.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter


  #  intl_translation: ^0.17.5
  build_runner: ^2.0.6
  hive_generator: ^1.1.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/res/images/logo.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/res/images/logo.jpg"

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
        - asset: assets/fonts/helveticaneuebold.ttf
        - asset: assets/fonts/helveticaneuebolditalic.ttf
        - asset: assets/fonts/helveticaneuecondensedblack.ttf
        - asset: assets/fonts/helveticaneuecondensedbold.ttf
        - asset: assets/fonts/helveticaneueitalic.ttf
        - asset: assets/fonts/helveticaneuelight.ttf
        - asset: assets/fonts/helveticaneuelightitalic.ttf
        - asset: assets/fonts/helveticaneuemedium.ttf
        - asset: assets/fonts/helveticaneueultralight.ttf
        - asset: assets/fonts/helveticaneueultralightitalic.ttf

  assets:
    - lib/res/strings/
    - lib/res/images/
    - assets/sounds/
    - lib/res/strings/en.json
    - lib/res/strings/vi.json
    - lib/res/strings/Question_Data.json