name: the_enest_english_grammar_test
description: The Enest English Grammar Test With Explanation

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  #Core dependencies
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_auth: ^0.20.0+1
  firebase_auth_oauth: ^0.2.4
  fluro: 1.6.3
  validate: ^1.7.0
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.2
  percent_indicator: ^2.1.1+1
  intl: ^0.16.0
  connectivity: ^0.4.8+1
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+17
  get: ^3.15.0
  http: ^0.12.2
  flutter_rating_bar: ^3.2.0+1
  google_fonts: ^1.1.1
  audioplayers: 0.17.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  animated_widgets: ^1.0.6
  aad_oauth: ^0.2.1
  rxdart: ^0.21.0
  websafe_svg: ^1.1.4
  confetti: ^0.5.4+1
  dio: ^3.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter


  #  intl_translation: ^0.17.5
  build_runner: ^1.3.1
  flutter_launcher_icons: ^0.7.4
  hive_generator: ^0.8.2
  uuid: ^2.0.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/res/images/ic_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/res/images/ic_logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/res/strings/
    - lib/res/images/
    - assets/sounds/
    - lib/res/strings/en.json
    - lib/res/strings/vi.json
    - lib/res/strings/Question_Data.json